name: Update KLeague Schedule

on:
  schedule:
    - cron: '0 0 * * *'   # 매일 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Restore Firebase Key
      run: printf '%s' "${{ secrets.FIREBASE_KEY }}" > serviceAccountKey.json

    - name: Run Crawler
      env:
        FIREBASE_BUCKET: kicksense-19c1d.appspot.com
      run: python kleague_crawler.py

    - name: Debug Firebase Key
      run: |
        printf '%s' "${{ secrets.FIREBASE_KEY }}" | head -n 5
        
    - name: Check Key Format
      run: cat serviceAccountKey.json | head -n 10

    # ✅ 추가: 실제로 복원된 파일 내용 확인
    - name: Debug Check Firebase Key
      run: |
        echo "----- serviceAccountKey.json 시작 -----"
        head -n 10 serviceAccountKey.json
        echo "----- serviceAccountKey.json 끝 -----"  

